{% set name = "python-lmdb" %}
{% set pypi_name = "lmdb" %}
{% set github_name = "py-lmdb" %}
{% set version = "1.2.1" %}
{% set sha256 = "470dde9838802e403cb0bf201e3af7e0ee4f027c1ec2d3b3b34dbedfc85f702f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ github_name }}_{{ version }}.zip
  url: https://github.com/dw/{{ github_name }}/archive/{{ github_name }}_{{ version }}.zip
  sha256: {{ sha256 }}
  patches:
    # 4/29/2021: Make map resize test more robust for weird-page-size OSs (After a new release 1.2.2 this patch should be deleted!):
    # Ubuntu on PPC64LE has a 64K page size.  This impacts the minimum map
    # size for an environment, as well as how fast a environment fills up. 
    - 506a5345c061b6a859cc73e60694f3ebcfbd4ba9.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - patch-ng
    - pip
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - lmdb
  commands:
    - py.test tests

about:
  home: https://lmdb.readthedocs.io/
  license: OpenLDAP
  license_family: Other
  license_file: LICENSE
  summary: "Universal Python binding for the LMDB 'Lightning' Database"
  description: |
    LMDB is a fast, memory-efficient, embedded key-value store (it does
    not require running an external daemon).
    With memory-mapped files, it has the read performance of a pure
    in-memory database while retaining the persistence of standard
    disk-based databases.
    python-lmdb is a Python binding for LMDB including a bundled
    version of LMDB.
  doc_url: https://lmdb.readthedocs.io/
  dev_url: https://github.com/dw/py-lmdb/

extra:
  recipe-maintainers:
    - pitrou
