travis:
  secure:
    BINSTAR_TOKEN: SHCuocjIzbBJjnNoXb17e/0Z1gY4sm8RZyBkPmWc9Yy1cegcSvvZpe+xTgtCFqks+yKN5WuJx47/pO0KKT72oqaJ+azr0w00WofEjA6o4kRrqOP0xw0azgbdaXj8aw2DFAq8T8KAKORmVYVAt4aC0FaB+4hddH4ZoK2CgW7y/sIoYnHsZmsGpBO5hzruXTE5BfltVuzDot1e+lGeyfS6/1OUnh1eXg8DLeMzZHJwKf+van7gJ7Og88ZEnXe3xiKrSntSjxqR+D7gc77HOnsuvtz2OqzEMoJ8y8/5ll3jg9XqriLqHnLt0RAsBjDwlzR6yLXA0NQDkHLTw/RtXEaijlIaD/O+EbQnlR8YQ+aYxITcktwMkO7biEqXLD3WAC35j1NynUk+6ttqnQYnYRaExQGWqnOrJfFon45jQI3NSE4uTNjTbka6JUd7FwLEQrDxGzbPvgBcgL0GnfCwYy8m179ScNdpAQfCmXaYCePsXAG9I1pnQHX+w2xxSznqMIPHZvBm5KtZPhC8LO0NpaKEqAEzKpQOpaQYEf1wbsHBob31eXEy92BD4mslLuQ/r1JWsW7vdKLLDiwnAYAULOKxLTk1hHWcY5t6hdzuDZpDj2OV5RToC7rEeIouN/eYggmQWaw+eoWFEiOhJeLahooKepqRfkWLxRiov0NxoRP523Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
